name: grafana-instance-dev

services:
  grafana:
    image: grafana/grafana:10.4.1
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_USER:-admin}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_PASSWORD:-admin}
    user: 
      "472:472"
    restart: 
      unless-stopped
    env_file:
      - .env
    networks:
      - monitoring-net

networks:
  monitoring-net:
    driver: bridge

volumes:
  grafana-data:
    driver: local
