name: grafana-instance

services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
      # Mount your GCP service account credentials
      # - ./gcp-credentials.json:/etc/grafana/gcp-credentials.json:ro
      - ./config/bq-keyfile.json:/etc/grafana/gcp-credentials.json:ro
    environment:
      # Basic Grafana configuration
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=securepassword  # Change this in production
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SERVER_ROOT_URL=http://localhost:3000
      
      # GCP Authentication config
      - GF_AUTH_GCE_ENABLED=true
      - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=grafana-bigquery-datasource
      
      # Optional: Uncomment to enable alerting
      - GF_UNIFIED_ALERTING_ENABLED=true
      
    networks:
      - grafana-network

volumes:
  grafana-storage:
    driver: local

networks:
  grafana-network:
    driver: bridge