# Common Docker Compose Configuration Template
# This file defines reusable configurations that can be applied to any service
# without specifying Docker images, making it truly environment-agnostic

# Common environment configurations
x-common-security-env: &common-security-env
  # Security Configuration
  - GF_SECURITY_COOKIE_SECURE=true
  - GF_SECURITY_COOKIE_SAMESITE=strict
  - GF_SECURITY_DISABLE_GRAVATAR=true
  - GF_SECURITY_STRICT_TRANSPORT_SECURITY=true
  - GF_SECURITY_STRICT_TRANSPORT_SECURITY_MAX_AGE_SECONDS=31536000
  - GF_SECURITY_X_CONTENT_TYPE_OPTIONS=true
  - GF_SECURITY_X_XSS_PROTECTION=true
  - GF_SECURITY_CONTENT_SECURITY_POLICY=true

x-common-logging-env: &common-logging-env
  # Logging Configuration
  - GF_LOG_MODE=file
  - GF_LOG_LEVEL=${GRAFANA_LOG_LEVEL:-info}
  - GF_LOG_FILTERS=${GRAFANA_LOG_FILTERS:-}

x-common-session-env: &common-session-env
  # Session Configuration
  - GF_SESSION_PROVIDER=file
  - GF_SESSION_COOKIE_SECURE=true
  - GF_SESSION_COOKIE_NAME=grafana_sess

x-common-user-env: &common-user-env
  # User Management
  - GF_USERS_ALLOW_SIGN_UP=false
  - GF_USERS_ALLOW_ORG_CREATE=false
  - GF_USERS_AUTO_ASSIGN_ORG=true
  - GF_USERS_AUTO_ASSIGN_ORG_ROLE=Viewer

x-common-auth-env: &common-auth-env
  # Authentication Configuration
  - GF_AUTH_ANONYMOUS_ENABLED=false
  - GF_AUTH_DISABLE_LOGIN_FORM=false

x-database-env: &database-env
  # Database Configuration
  - GF_DATABASE_TYPE=${GRAFANA_DB_TYPE:-sqlite3}
  - GF_DATABASE_HOST=${GRAFANA_DB_HOST:-}
  - GF_DATABASE_NAME=${GRAFANA_DB_NAME:-grafana}
  - GF_DATABASE_USER=${GRAFANA_DB_USER:-}
  - GF_DATABASE_PASSWORD=${GRAFANA_DB_PASSWORD:-}
  
  # PostgreSQL Database Connections
  - POSTGRES_DB1_HOST=${POSTGRES_DB1_HOST}
  - POSTGRES_DB1_PORT=${POSTGRES_DB1_PORT}
  - POSTGRES_DB1_DATABASE=${POSTGRES_DB1_DATABASE}
  - POSTGRES_DB1_USER=${POSTGRES_DB1_USER}
  - POSTGRES_DB1_PASSWORD=${POSTGRES_DB1_PASSWORD}
  
  - POSTGRES_DB2_HOST=${POSTGRES_DB2_HOST}
  - POSTGRES_DB2_PORT=${POSTGRES_DB2_PORT}
  - POSTGRES_DB2_DATABASE=${POSTGRES_DB2_DATABASE}
  - POSTGRES_DB2_USER=${POSTGRES_DB2_USER}
  - POSTGRES_DB2_PASSWORD=${POSTGRES_DB2_PASSWORD}

x-smtp-env: &smtp-env
  # SMTP Configuration
  - GF_SMTP_ENABLED=${GRAFANA_SMTP_ENABLED:-false}
  - GF_SMTP_HOST=${GRAFANA_SMTP_HOST:-}
  - GF_SMTP_USER=${GRAFANA_SMTP_USER:-}
  - GF_SMTP_PASSWORD=${GRAFANA_SMTP_PASSWORD:-}
  - GF_SMTP_FROM_ADDRESS=${GRAFANA_SMTP_FROM:-grafana@example.com}

# Combined all common environment variables into a single anchor
x-all-common-env: &all-common-env
  # Grafana-specific environment variables
  - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD:-admin}
  - GF_SECURITY_ADMIN_USER=${GRAFANA_USER:-admin}
  - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource,grafana-piechart-panel,grafana-worldmap-panel
  - GF_SERVER_ROOT_URL=${GRAFANA_ROOT_URL:-http://localhost:3000}
  - GF_SERVER_DOMAIN=${GRAFANA_DOMAIN:-localhost}
  - GF_SERVER_ENFORCE_DOMAIN=true
  - GF_SECURITY_ALLOW_EMBEDDING=true

  # Security Configuration
  - GF_SECURITY_COOKIE_SECURE=true
  - GF_SECURITY_COOKIE_SAMESITE=strict
  - GF_SECURITY_DISABLE_GRAVATAR=true
  - GF_SECURITY_STRICT_TRANSPORT_SECURITY=true
  - GF_SECURITY_STRICT_TRANSPORT_SECURITY_MAX_AGE_SECONDS=31536000
  - GF_SECURITY_X_CONTENT_TYPE_OPTIONS=true
  - GF_SECURITY_X_XSS_PROTECTION=true
  - GF_SECURITY_CONTENT_SECURITY_POLICY=true
  
  # Logging Configuration
  - GF_LOG_MODE=file
  - GF_LOG_LEVEL=${GRAFANA_LOG_LEVEL:-info}
  - GF_LOG_FILTERS=${GRAFANA_LOG_FILTERS:-}
  
  # Session Configuration
  - GF_SESSION_PROVIDER=file
  - GF_SESSION_COOKIE_SECURE=true
  - GF_SESSION_COOKIE_NAME=grafana_sess
  
  # User Management
  - GF_USERS_ALLOW_SIGN_UP=false
  - GF_USERS_ALLOW_ORG_CREATE=false
  - GF_USERS_AUTO_ASSIGN_ORG=true
  - GF_USERS_AUTO_ASSIGN_ORG_ROLE=Viewer
  
  # Authentication Configuration
  - GF_AUTH_ANONYMOUS_ENABLED=false
  - GF_AUTH_DISABLE_LOGIN_FORM=false
  
  # Database Configuration
  - GF_DATABASE_TYPE=${GRAFANA_DB_TYPE:-sqlite3}
  - GF_DATABASE_HOST=${GRAFANA_DB_HOST:-}
  - GF_DATABASE_NAME=${GRAFANA_DB_NAME:-grafana}
  - GF_DATABASE_USER=${GRAFANA_DB_USER:-}
  - GF_DATABASE_PASSWORD=${GRAFANA_DB_PASSWORD:-}
  
  # PostgreSQL Database Connections
  - POSTGRES_DB1_HOST=${POSTGRES_DB1_HOST}
  - POSTGRES_DB1_PORT=${POSTGRES_DB1_PORT}
  - POSTGRES_DB1_DATABASE=${POSTGRES_DB1_DATABASE}
  - POSTGRES_DB1_USER=${POSTGRES_DB1_USER}
  - POSTGRES_DB1_PASSWORD=${POSTGRES_DB1_PASSWORD}
  - POSTGRES_DB2_HOST=${POSTGRES_DB2_HOST}
  - POSTGRES_DB2_PORT=${POSTGRES_DB2_PORT}
  - POSTGRES_DB2_DATABASE=${POSTGRES_DB2_DATABASE}
  - POSTGRES_DB2_USER=${POSTGRES_DB2_USER}
  - POSTGRES_DB2_PASSWORD=${POSTGRES_DB2_PASSWORD}
  
  # SMTP Configuration
  - GF_SMTP_ENABLED=${GRAFANA_SMTP_ENABLED:-false}
  - GF_SMTP_HOST=${GRAFANA_SMTP_HOST:-}
  - GF_SMTP_USER=${GRAFANA_SMTP_USER:-}
  - GF_SMTP_PASSWORD=${GRAFANA_SMTP_PASSWORD:-}
  - GF_SMTP_FROM_ADDRESS=${GRAFANA_SMTP_FROM:-grafana@example.com} 