global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:

  # Monitor for production environments
  - job_name: 'postgres-exporter-prod'
    file_sd_configs:
      - files:
          - '/etc/prometheus/targets/prod.json'
        refresh_interval: 5s
    metrics_path: /probe
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: postgres-exporter:9187