apiVersion: 1

datasources:
  # Neon PostgreSQL Database 1
  - name: "${NEON_DB1_NAME:-Neon-Production}"
    type: postgres
    access: proxy
    url: "${NEON_DB1_HOST:-your-neon-host1.neon.tech}:${NEON_DB1_PORT:-5432}"
    database: "${NEON_DB1_DATABASE:-neondb}"
    user: "${NEON_DB1_USER:-your-username}"
    secureJsonData:
      password: "${NEON_DB1_PASSWORD:-your-password}"
    jsonData:
      sslmode: "require"  # Neon requires SSL
      maxOpenConns: 100
      maxIdleConns: 25
      maxIdleConnsAuto: true
      connMaxLifetime: 14400
      postgresVersion: 1500  # PostgreSQL 15
      timescaledb: false
    editable: true
    orgId: 1
    isDefault: true
    version: 1
    uid: neon-db1

  # Neon PostgreSQL Database 2
  - name: "${NEON_DB2_NAME:-Neon-Staging}"
    type: postgres
    access: proxy
    url: "${NEON_DB2_HOST:-your-neon-host2.neon.tech}:${NEON_DB2_PORT:-5432}"
    database: "${NEON_DB2_DATABASE:-neondb}"
    user: "${NEON_DB2_USER:-your-username}"
    secureJsonData:
      password: "${NEON_DB2_PASSWORD:-your-password}"
    jsonData:
      sslmode: "require"
      maxOpenConns: 50
      maxIdleConns: 15
      maxIdleConnsAuto: true
      connMaxLifetime: 14400
      postgresVersion: 1500
      timescaledb: false
    editable: true
    orgId: 1
    isDefault: false
    version: 1
    uid: neon-db2

  # Neon PostgreSQL Database 3
  - name: "${NEON_DB3_NAME:-Neon-Analytics}"
    type: postgres
    access: proxy
    url: "${NEON_DB3_HOST:-your-neon-host3.neon.tech}:${NEON_DB3_PORT:-5432}"
    database: "${NEON_DB3_DATABASE:-neondb}"
    user: "${NEON_DB3_USER:-your-username}"
    secureJsonData:
      password: "${NEON_DB3_PASSWORD:-your-password}"
    jsonData:
      sslmode: "require"
      maxOpenConns: 75
      maxIdleConns: 20
      maxIdleConnsAuto: true
      connMaxLifetime: 14400
      postgresVersion: 1500
      timescaledb: false
    editable: true
    orgId: 1
    isDefault: false
    version: 1
    uid: neon-db3 