# Example: How to use the common configuration template
# This demonstrates creating different environments using the common template

# Import common configurations
include:
  - compose.common.yml

name: grafana-multi-environment

services:
  # Production Grafana using stable image
  grafana-prod:
    <<: *grafana-service-template
    image: grafana/grafana:12.0.1
    container_name: grafana-prod
    environment:
      # Service-specific admin config
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PROD_PASSWORD:-admin}
      - GF_SECURITY_ADMIN_USER=${GRAFANA_PROD_USER:-admin}
      
      # Service-specific server config
      - GF_SERVER_ROOT_URL=${GRAFANA_PROD_ROOT_URL:-http://localhost:3000}
      - GF_SERVER_DOMAIN=${GRAFANA_PROD_DOMAIN:-localhost}
      - GF_SERVER_ENFORCE_DOMAIN=true
      - GF_SECURITY_ALLOW_EMBEDDING=true
      
      # Plugin configuration
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource,grafana-piechart-panel
      
      # Merge in common environment variables
      <<: [*common-security-env, *common-logging-env, *common-session-env, *common-user-env, *common-auth-env, *database-env, *smtp-env]
    ports:
      - "3000:3000"

  # Development Grafana using latest image
  grafana-dev:
    <<: *grafana-service-template
    image: grafana/grafana:latest
    container_name: grafana-dev
    environment:
      # Service-specific admin config
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_DEV_PASSWORD:-dev}
      - GF_SECURITY_ADMIN_USER=${GRAFANA_DEV_USER:-dev}
      
      # Service-specific server config
      - GF_SERVER_ROOT_URL=${GRAFANA_DEV_ROOT_URL:-http://localhost:3001}
      - GF_SERVER_DOMAIN=${GRAFANA_DEV_DOMAIN:-localhost}
      - GF_SERVER_ENFORCE_DOMAIN=false
      - GF_SECURITY_ALLOW_EMBEDDING=true
      
      # Development plugins (including beta ones)
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource,grafana-piechart-panel,grafana-worldmap-panel
      
      # Allow sign-up for development
      - GF_USERS_ALLOW_SIGN_UP=true
      - GF_USERS_ALLOW_ORG_CREATE=true
      
      # Merge in other common environment variables
      <<: [*common-security-env, *common-logging-env, *common-session-env, *common-auth-env, *database-env, *smtp-env]
    ports:
      - "3001:3000"

  # Testing Grafana using specific test image
  grafana-test:
    <<: *grafana-service-template
    image: grafana/grafana:11.2.0
    container_name: grafana-test
    environment:
      # Service-specific admin config
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_TEST_PASSWORD:-test}
      - GF_SECURITY_ADMIN_USER=${GRAFANA_TEST_USER:-test}
      
      # Service-specific server config
      - GF_SERVER_ROOT_URL=${GRAFANA_TEST_ROOT_URL:-http://localhost:3002}
      - GF_SERVER_DOMAIN=${GRAFANA_TEST_DOMAIN:-localhost}
      - GF_SERVER_ENFORCE_DOMAIN=false
      - GF_SECURITY_ALLOW_EMBEDDING=true
      
      # Minimal plugins for testing
      - GF_INSTALL_PLUGINS=grafana-clock-panel
      
      # Enable anonymous access for testing
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
      
      # Merge in other common environment variables
      <<: [*common-security-env, *common-logging-env, *common-session-env, *common-user-env, *database-env, *smtp-env]
    ports:
      - "3002:3000"

  # Custom Grafana using enterprise image
  grafana-enterprise:
    <<: *grafana-service-template
    image: grafana/grafana-enterprise:12.0.1
    container_name: grafana-enterprise
    environment:
      # Service-specific admin config
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ENT_PASSWORD:-enterprise}
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ENT_USER:-enterprise}
      
      # Service-specific server config
      - GF_SERVER_ROOT_URL=${GRAFANA_ENT_ROOT_URL:-http://localhost:3003}
      - GF_SERVER_DOMAIN=${GRAFANA_ENT_DOMAIN:-localhost}
      - GF_SERVER_ENFORCE_DOMAIN=true
      - GF_SECURITY_ALLOW_EMBEDDING=false
      
      # Enterprise plugins
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource,grafana-piechart-panel,grafana-worldmap-panel,grafana-image-renderer
      
      # Enterprise features
      - GF_ENTERPRISE_LICENSE_TEXT=${GRAFANA_ENTERPRISE_LICENSE:-}
      
      # Merge in common environment variables
      <<: [*common-security-env, *common-logging-env, *common-session-env, *common-user-env, *common-auth-env, *database-env, *smtp-env]
    ports:
      - "3003:3000" 