name: grafana-monitoring-prod



services:
  grafana:
    image: grafana/grafana:12.0.1
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
      - ./grafana/data:/var/lib/grafana
      - ./grafana/logs:/var/log/grafana
      - ./grafana/plugins:/var/lib/grafana/plugins
    
    environment:
      # Admin Configuration
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD:-admin}
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USER:-admin}
      
      # Plugin Configuration
      # Pre-install useful plugins on container startup
      # Add more plugins as comma-separated list
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource,grafana-piechart-panel,grafana-worldmap-panel
      
      # Security Configuration
      # Allow embedding Grafana in iframes (set to false if not needed)
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_SECURITY_COOKIE_SECURE=true
      - GF_SECURITY_COOKIE_SAMESITE=strict
      - GF_SECURITY_DISABLE_GRAVATAR=true
      
      # Enable HTTP Strict Transport Security (HSTS) for HTTPS enforcement
      - GF_SECURITY_STRICT_TRANSPORT_SECURITY=true
      - GF_SECURITY_STRICT_TRANSPORT_SECURITY_MAX_AGE_SECONDS=31536000  # 1 year
      
      # Additional security headers to prevent XSS and content sniffing
      - GF_SECURITY_X_CONTENT_TYPE_OPTIONS=true
      - GF_SECURITY_X_XSS_PROTECTION=true
      - GF_SECURITY_CONTENT_SECURITY_POLICY=true
      
      # Server Configuration
      # Root URL for Grafana (important for reverse proxy setups)
      - GF_SERVER_ROOT_URL=${GRAFANA_ROOT_URL:-http://localhost:3000}
      - GF_SERVER_DOMAIN=${GRAFANA_DOMAIN:-localhost}
      - GF_SERVER_ENFORCE_DOMAIN=true
      
      # Database Configuration
      # Database type: sqlite3 (default), mysql, postgres
      # For production, consider using external PostgreSQL or MySQL
      - GF_DATABASE_TYPE=${GRAFANA_DB_TYPE:-sqlite3}
      
      # Database connection settings (only needed for external databases)
      - GF_DATABASE_HOST=${GRAFANA_DB_HOST:-}        # e.g., postgres:5432
      - GF_DATABASE_NAME=${GRAFANA_DB_NAME:-grafana}  # Database name
      - GF_DATABASE_USER=${GRAFANA_DB_USER:-}         # Database username
      - GF_DATABASE_PASSWORD=${GRAFANA_DB_PASSWORD:-} # Database password
      
      # Logging Configuration
      # Log to file instead of console for better log management
      - GF_LOG_MODE=file
      - GF_LOG_LEVEL=${GRAFANA_LOG_LEVEL:-info}
      - GF_LOG_FILTERS=${GRAFANA_LOG_FILTERS:-}
      
      # Session Configuration
      # Use file-based sessions (alternative: redis, mysql, postgres)
      - GF_SESSION_PROVIDER=file
      - GF_SESSION_COOKIE_SECURE=true
      - GF_SESSION_COOKIE_NAME=grafana_sess
      
      # User Management
      # Disable user registration for security
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_USERS_ALLOW_ORG_CREATE=false
      - GF_USERS_AUTO_ASSIGN_ORG=true
      - GF_USERS_AUTO_ASSIGN_ORG_ROLE=Viewer
      
      # Authentication Configuration
      # Disable anonymous access for security
      - GF_AUTH_ANONYMOUS_ENABLED=false
      - GF_AUTH_DISABLE_LOGIN_FORM=false
      
      # SMTP Configuration (Email Notifications)
      # Enable SMTP for email notifications
      - GF_SMTP_ENABLED=${GRAFANA_SMTP_ENABLED:-false}
      
      # SMTP server configuration
      - GF_SMTP_HOST=${GRAFANA_SMTP_HOST:-}
      - GF_SMTP_USER=${GRAFANA_SMTP_USER:-}
      - GF_SMTP_PASSWORD=${GRAFANA_SMTP_PASSWORD:-}
      - GF_SMTP_FROM_ADDRESS=${GRAFANA_SMTP_FROM:-grafana@example.com}
       
      - POSTGRES_DB1_HOST=${POSTGRES_DB1_HOST}
      - POSTGRES_DB1_PORT=${POSTGRES_DB1_PORT}
      - POSTGRES_DB1_DATABASE=${POSTGRES_DB1_DATABASE}
      - POSTGRES_DB1_USER=${POSTGRES_DB1_USER}
      - POSTGRES_DB1_PASSWORD=${POSTGRES_DB1_PASSWORD}
      
      - POSTGRES_DB2_HOST=${POSTGRES_DB2_HOST}
      - POSTGRES_DB2_PORT=${POSTGRES_DB2_PORT}
      - POSTGRES_DB2_DATABASE=${POSTGRES_DB2_DATABASE}
      - POSTGRES_DB2_USER=${POSTGRES_DB2_USER}
      - POSTGRES_DB2_PASSWORD=${POSTGRES_DB2_PASSWORD}
    
    restart: unless-stopped
    env_file:
      - .env
    
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
        reservations:
          memory: 512M
          cpus: '0.25'
    
    # Security Options
    # Prevent privilege escalation within container
    security_opt:
      - no-new-privileges:true
    
    # Allow write access (Grafana needs to write to data directory)
    # Set to true only if using external storage for all data
    read_only: false
    
    # Run as grafana user (UID:GID 472:472) instead of root
    # This reduces security risks from container compromise
    user: "472:472"
    
    # Health Check Configuration
    # Monitor container health using Grafana's health API
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3000/api/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    
    # Container Labels
    # Labels for service discovery and management
    labels:
      # Traefik reverse proxy configuration
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.rule=Host(`${GRAFANA_DOMAIN:-localhost}`)"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"
      
      # Watchtower auto-update configuration
      - "com.centurylinklabs.watchtower.enable=true"
      
      # Custom labels for organization
      - "app=grafana"
      - "environment=production"
    
    # Logging Configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        labels: "app,environment"
    
    networks:
      - monitoring
      - default

# Network Definitions
networks:
  monitoring:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: br-monitoring
    ipam:
      config:
        - subnet: 172.20.0.0/16
  
  # Default network for general connectivity
  default:
    driver: bridge

# Volume Definitions
volumes:
  grafana_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./grafana/data
  
  grafana_logs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./grafana/logs 